
server:
    port: 8090

eureka:
  instance:
    appname: eureka.server.01

  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: eureka.server
  redis:
    database: 0
    host: 127.0.0.1 
    password: 
    port: 6379    
  pool:
    max-idle: 8   
    min-idle: 0    
    max-active: 8    
    max-wait: -1
  sentinel: 
    master:  
    nodes:  

  datasource: 
    name: spring_boot_mybatis
    url: jdbc:mysql://localhost:3306/vivi?useUnicode=true&characterEncoding=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: vivi
    password: viviangel
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
logging: 
    config: classpath:config/log4j2.xml